### ISSUE TITLE
Issue with PEM keys

### ISSUE THREAD

**Issue by mortzdk** [kelvinmo/simplejwt#10]
After update 0.2.2, I am no longer able to decode PEM keys correctly. 

I get the following error:
Key not found or is invalid

My unittests uses the same set of test keys always and while they work in version 0.2.1, they do not work in 0.2.2

[keys.zip](https://github.com/kelvinmo/simplejwt/files/2836750/keys.zip)

**Comment by kelvinmo** [comment]
The code for loading PEM-encoded RSA keys was changed from 0.2.1 and 0.2.2.  See commit 423b539 for more details.  However, this seems to have broken the code to translate the key back to PEM-format, which is required by OpenSSL.

**Comment by kelvinmo** [comment]
This should be fixed in v0.2.3

**Comment by mortzdk** [comment]
Hi again!

Thanks for the quick response.

Still some issues:
Commit 02c542a7d3019c83b6ff15ba3395ded2cd982382 contains a `var_dump`.

Furthermore it does not seem to fix the issue, as I still receive the same exception.
[JWTTest.zip](https://github.com/kelvinmo/simplejwt/files/2841197/JWTTest.zip)



Attached is an updated JWTTest.php file using the keys provided earlier. This corresponds to what I am doing.

// Morten

**Comment by kelvinmo** [comment]
OK - there are two issues that will cause the unit test to fail.

_Firstly_, simplejwt automatically inserts a `kid` header and a `iat` claim to all JWTs it creates, unless you explicitly disable them.  When you import an RSA key from a PEM file, simplejwt automatically assigns a `kid` based on the RSA public key parameters.  However, due to an incorrect fix in 02c542a a public key PEM is decoded differently from a private key PEM, resulting in a `kid` mismatch.  Thus when you try to decode the JWT, it tries to find the public key via the `kid` header, but couldn't find it in the key set because the public key has a different `kid`.

You can test this by changing line 25 in your unit test to:

```php
return $jwt->encode($keyset, null, false);
```

The `kid` mismatch issue is fixed in 1546539.

_Secondly_, line 184 in your unit test will always fail because `$jwt->getClaims()` includes an automatically inserted `iat` claim which is missing from `$claims`.

**Comment by mortzdk** [comment]
Hi Kelvin,

Thanks again for the quick reply.

First of all commit 154653906dcbd8ac22b5a424924ee3c6700e1920 fixes the issue and passes my tests.

As for the "secondly" part, that was a mistake on my part, sorry for the inconvenience!

I look forward to using your library in the future.

// Morten
